### ISSUE TITLE
out of memory when val during training

### ISSUE THREAD

**Issue by MSC19950601** [openseg-group/openseg.pytorch#41]
I met OOM problem when validate during training phase.
Here is the log:
World size: 4
['--configs', 'configs/cityscapes/R_101_D_8.json', '--drop_last', 'y', '--phase', 'train', '--gathered', 'n', '--loss_balance', 'y', '--log_to_file', 'n', '--backbone', 'deepbase_resnet101_dilated8', '--model_name', 'base_ocnet', '--gpu', '0', '1', '2', '3', '--distributed', '--data_dir', './dataset/cityscapes', '--loss_type', 'fs_auxce_loss', '--max_iters', '40000', '--checkpoints_name', 'base_ocnet_deepbase_resnet101_dilated8_20201029', '--pretrained', './pretrained_model/resnet101-imagenet.pth']
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
2020-10-30 23:23:59,797 INFO    [offset_helper.py, 54] engery/max-distance: 5 engery/min-distance: 0
2020-10-30 23:23:59,797 INFO    [offset_helper.py, 61] direction/num_classes: 8 scale: 1
2020-10-30 23:23:59,797 INFO    [offset_helper.py, 66] c4 align axis: False
2020-10-30 23:23:59,800 INFO    [offset_helper.py, 54] engery/max-distance: 5 engery/min-distance: 0
2020-10-30 23:23:59,800 INFO    [offset_helper.py, 61] direction/num_classes: 8 scale: 1
2020-10-30 23:23:59,800 INFO    [offset_helper.py, 66] c4 align axis: False
2020-10-30 23:23:59,808 INFO    [module_runner.py, 44] BN Type is inplace_abn.
2020-10-30 23:23:59,808 INFO    [__init__.py, 17] Using evaluator: StandardEvaluator
2020-10-30 23:23:59,811 INFO    [module_runner.py, 44] BN Type is inplace_abn.
2020-10-30 23:23:59,811 INFO    [__init__.py, 17] Using evaluator: StandardEvaluator
2020-10-30 23:24:00,360 INFO    [module_helper.py, 136] Loading pretrained model:./pretrained_model/resnet101-imagenet.pth
2020-10-30 23:24:00,361 INFO    [module_helper.py, 136] Loading pretrained model:./pretrained_model/resnet101-imagenet.pth
2020-10-30 23:24:00,752 INFO    [offset_helper.py, 54] engery/max-distance: 5 engery/min-distance: 0
2020-10-30 23:24:00,752 INFO    [offset_helper.py, 61] direction/num_classes: 8 scale: 1
2020-10-30 23:24:00,752 INFO    [offset_helper.py, 66] c4 align axis: False
2020-10-30 23:24:00,759 INFO    [offset_helper.py, 54] engery/max-distance: 5 engery/min-distance: 0
2020-10-30 23:24:00,760 INFO    [offset_helper.py, 61] direction/num_classes: 8 scale: 1
2020-10-30 23:24:00,760 INFO    [offset_helper.py, 66] c4 align axis: False
2020-10-30 23:24:00,763 INFO    [module_runner.py, 44] BN Type is inplace_abn.
2020-10-30 23:24:00,763 INFO    [__init__.py, 17] Using evaluator: StandardEvaluator
2020-10-30 23:24:00,771 INFO    [module_runner.py, 44] BN Type is inplace_abn.
2020-10-30 23:24:00,771 INFO    [__init__.py, 17] Using evaluator: StandardEvaluator
2020-10-30 23:24:01,344 INFO    [module_helper.py, 136] Loading pretrained model:./pretrained_model/resnet101-imagenet.pth
2020-10-30 23:24:01,349 INFO    [module_helper.py, 136] Loading pretrained model:./pretrained_model/resnet101-imagenet.pth
2020-10-30 23:24:06,815 INFO    [trainer.py, 78] Params Group Method: None
2020-10-30 23:24:06,816 INFO    [trainer.py, 78] Params Group Method: None
2020-10-30 23:24:06,816 INFO    [trainer.py, 78] Params Group Method: None
2020-10-30 23:24:06,816 INFO    [trainer.py, 78] Params Group Method: None
2020-10-30 23:24:06,817 INFO    [optim_scheduler.py, 66] Use lambda_poly policy with default power 0.9
2020-10-30 23:24:06,817 INFO    [data_loader.py, 131] use the DefaultLoader for train...
2020-10-30 23:24:06,818 INFO    [optim_scheduler.py, 66] Use lambda_poly policy with default power 0.9
2020-10-30 23:24:06,818 INFO    [optim_scheduler.py, 66] Use lambda_poly policy with default power 0.9
2020-10-30 23:24:06,818 INFO    [data_loader.py, 131] use the DefaultLoader for train...
2020-10-30 23:24:06,818 INFO    [optim_scheduler.py, 66] Use lambda_poly policy with default power 0.9
2020-10-30 23:24:06,818 INFO    [data_loader.py, 131] use the DefaultLoader for train...
2020-10-30 23:24:06,818 INFO    [data_loader.py, 131] use the DefaultLoader for train...
2020-10-30 23:24:06,855 INFO    [data_loader.py, 164] use DefaultLoader for val ...
2020-10-30 23:24:06,855 INFO    [data_loader.py, 164] use DefaultLoader for val ...
2020-10-30 23:24:06,856 INFO    [data_loader.py, 164] use DefaultLoader for val ...
2020-10-30 23:24:06,857 INFO    [data_loader.py, 164] use DefaultLoader for val ...
2020-10-30 23:24:06,861 INFO    [loss_manager.py, 54] use loss: fs_auxce_loss.
2020-10-30 23:24:06,861 INFO    [loss_manager.py, 54] use loss: fs_auxce_loss.
2020-10-30 23:24:06,861 INFO    [loss_manager.py, 39] use distributed loss
2020-10-30 23:24:06,861 INFO    [loss_manager.py, 39] use distributed loss
2020-10-30 23:24:06,863 INFO    [loss_manager.py, 54] use loss: fs_auxce_loss.
2020-10-30 23:24:06,863 INFO    [loss_manager.py, 54] use loss: fs_auxce_loss.
2020-10-30 23:24:06,863 INFO    [loss_manager.py, 39] use distributed loss
2020-10-30 23:24:06,863 INFO    [loss_manager.py, 39] use distributed loss
2020-10-30 23:24:07,060 INFO    [data_helper.py, 119] Input keys: ['img']
2020-10-30 23:24:07,061 INFO    [data_helper.py, 120] Target keys: ['labelmap']
2020-10-30 23:24:07,115 INFO    [data_helper.py, 119] Input keys: ['img']
2020-10-30 23:24:07,115 INFO    [data_helper.py, 120] Target keys: ['labelmap']
2020-10-30 23:24:07,117 INFO    [data_helper.py, 119] Input keys: ['img']
2020-10-30 23:24:07,117 INFO    [data_helper.py, 120] Target keys: ['labelmap']
2020-10-30 23:24:07,126 INFO    [data_helper.py, 119] Input keys: ['img']
2020-10-30 23:24:07,126 INFO    [data_helper.py, 120] Target keys: ['labelmap']
2020-10-30 23:24:18,010 INFO    [trainer.py, 219] Train Epoch: 0	Train Iteration: 10	Time 11.147s / 10iters, (1.115)	Forward Time 3.996s / 10iters, (0.400)	Backward Time 6.918s / 10iters, (0.692)	Loss Time 0.029s / 10iters, (0.003)	Data load 0.203s / 10iters, (0.020318)
Learning rate = [0.00999797497721687, 0.00999797497721687]	Loss = 3.54437590 (ave = 3.62284539)

2020-10-30 23:24:18,808 INFO    [trainer.py, 259] 0 images processed

2020-10-30 23:24:19,588 INFO    [trainer.py, 259] 0 images processed

2020-10-30 23:24:19,825 INFO    [trainer.py, 259] 0 images processed

2020-10-30 23:24:19,840 INFO    [trainer.py, 259] 0 images processed

Traceback (most recent call last):
  File "/home/kururu/github/openseg.pytorch/main.py", line 227, in <module>
    model.train()
  File "/home/kururu/github/openseg.pytorch/segmentor/trainer.py", line 365, in train
    self.__train()
  File "/home/kururu/github/openseg.pytorch/segmentor/trainer.py", line 240, in __train
    self.__val()
  File "/home/kururu/github/openseg.pytorch/segmentor/trainer.py", line 308, in __val
    outputs = self.seg_net(*inputs)
  File "/home/kururu/anaconda3/envs/kururudev-torch-1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kururu/anaconda3/envs/kururudev-torch-1-0/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 442, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/kururu/anaconda3/envs/kururudev-torch-1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kururu/github/openseg.pytorch/lib/models/nets/ocnet.py", line 58, in forward
    x = self.oc_module(x)
  File "/home/kururu/anaconda3/envs/kururudev-torch-1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kururu/github/openseg.pytorch/lib/models/modules/base_oc_block.py", line 153, in forward
    priors = [stage(feats) for stage in self.stages]
  File "/home/kururu/github/openseg.pytorch/lib/models/modules/base_oc_block.py", line 153, in <listcomp>
    priors = [stage(feats) for stage in self.stages]
  File "/home/kururu/anaconda3/envs/kururudev-torch-1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kururu/github/openseg.pytorch/lib/models/modules/base_oc_block.py", line 89, in forward
    sim_map = (self.key_channels**-.5) * sim_map
RuntimeError: CUDA out of memory. Tried to allocate 4.10 GiB (GPU 0; 10.91 GiB total capacity; 5.16 GiB already allocated; 3.28 GiB free; 229.69 MiB cached)
Traceback (most recent call last):
  File "/home/kururu/anaconda3/envs/kururudev-torch-1-0/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/kururu/anaconda3/envs/kururudev-torch-1-0/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/kururu/anaconda3/envs/kururudev-torch-1-0/lib/python3.6/site-packages/torch/distributed/launch.py", line 253, in <module>
    main()
  File "/home/kururu/anaconda3/envs/kururudev-torch-1-0/lib/python3.6/site-packages/torch/distributed/launch.py", line 249, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/kururu/anaconda3/envs/kururudev-torch-1-0/bin/python', '-u', '/home/kururu/github/openseg.pytorch/main.py', '--local_rank=3', '--configs', 'configs/cityscapes/R_101_D_8.json', '--drop_last', 'y', '--phase', 'train', '--gathered', 'n', '--loss_balance', 'y', '--log_to_file', 'n', '--backbone', 'deepbase_resnet101_dilated8', '--model_name', 'base_ocnet', '--gpu', '0', '1', '2', '3', '--distributed', '--data_dir', './dataset/cityscapes', '--loss_type', 'fs_auxce_loss', '--max_iters', '40000', '--checkpoints_name', 'base_ocnet_deepbase_resnet101_dilated8_20201029', '--pretrained', './pretrained_model/resnet101-imagenet.pth']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "main.py", line 178, in <module>
    handle_distributed(args_parser, os.path.expanduser(os.path.abspath(__file__)))
  File "/home/kururu/github/openseg.pytorch/lib/utils/distributed.py", line 56, in handle_distributed
    cmd=command_args)
subprocess.CalledProcessError: Command '['/home/kururu/anaconda3/envs/kururudev-torch-1-0/bin/python', '-u', '-m', 'torch.distributed.launch', '--nproc_per_node', '4', '/home/kururu/github/openseg.pytorch/main.py', '--configs', 'configs/cityscapes/R_101_D_8.json', '--drop_last', 'y', '--phase', 'train', '--gathered', 'n', '--loss_balance', 'y', '--log_to_file', 'n', '--backbone', 'deepbase_resnet101_dilated8', '--model_name', 'base_ocnet', '--gpu', '0', '1', '2', '3', '--distributed', '--data_dir', './dataset/cityscapes', '--loss_type', 'fs_auxce_loss', '--max_iters', '40000', '--checkpoints_name', 'base_ocnet_deepbase_resnet101_dilated8_20201029', '--pretrained', './pretrained_model/resnet101-imagenet.pth']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/home/kururu/github/openseg.pytorch/main.py", line 227, in <module>
    model.train()
  File "/home/kururu/github/openseg.pytorch/segmentor/trainer.py", line 365, in train
    self.__train()
  File "/home/kururu/github/openseg.pytorch/segmentor/trainer.py", line 240, in __train
    self.__val()
  File "/home/kururu/github/openseg.pytorch/segmentor/trainer.py", line 308, in __val
    outputs = self.seg_net(*inputs)
  File "/home/kururu/anaconda3/envs/kururudev-torch-1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kururu/anaconda3/envs/kururudev-torch-1-0/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 442, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/kururu/anaconda3/envs/kururudev-torch-1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kururu/github/openseg.pytorch/lib/models/nets/ocnet.py", line 58, in forward
    x = self.oc_module(x)
  File "/home/kururu/anaconda3/envs/kururudev-torch-1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kururu/github/openseg.pytorch/lib/models/modules/base_oc_block.py", line 153, in forward
    priors = [stage(feats) for stage in self.stages]
  File "/home/kururu/github/openseg.pytorch/lib/models/modules/base_oc_block.py", line 153, in <listcomp>
    priors = [stage(feats) for stage in self.stages]
  File "/home/kururu/anaconda3/envs/kururudev-torch-1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kururu/github/openseg.pytorch/lib/models/modules/base_oc_block.py", line 89, in forward
    sim_map = (self.key_channels**-.5) * sim_map
RuntimeError: CUDA out of memory. Tried to allocate 4.10 GiB (GPU 3; 10.92 GiB total capacity; 5.46 GiB already allocated; 1019.50 MiB free; 3.89 GiB cached)
Traceback (most recent call last):
  File "/home/kururu/github/openseg.pytorch/main.py", line 227, in <module>
    model.train()
  File "/home/kururu/github/openseg.pytorch/segmentor/trainer.py", line 365, in train
    self.__train()
  File "/home/kururu/github/openseg.pytorch/segmentor/trainer.py", line 240, in __train
    self.__val()
  File "/home/kururu/github/openseg.pytorch/segmentor/trainer.py", line 308, in __val
    outputs = self.seg_net(*inputs)
  File "/home/kururu/anaconda3/envs/kururudev-torch-1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kururu/anaconda3/envs/kururudev-torch-1-0/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 442, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/kururu/anaconda3/envs/kururudev-torch-1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kururu/github/openseg.pytorch/lib/models/nets/ocnet.py", line 58, in forward
    x = self.oc_module(x)
  File "/home/kururu/anaconda3/envs/kururudev-torch-1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kururu/github/openseg.pytorch/lib/models/modules/base_oc_block.py", line 153, in forward
    priors = [stage(feats) for stage in self.stages]
  File "/home/kururu/github/openseg.pytorch/lib/models/modules/base_oc_block.py", line 153, in <listcomp>
    priors = [stage(feats) for stage in self.stages]
  File "/home/kururu/anaconda3/envs/kururudev-torch-1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kururu/github/openseg.pytorch/lib/models/modules/base_oc_block.py", line 89, in forward
    sim_map = (self.key_channels**-.5) * sim_map
RuntimeError: CUDA out of memory. Tried to allocate 4.10 GiB (GPU 2; 10.92 GiB total capacity; 5.46 GiB already allocated; 1023.50 MiB free; 3.89 GiB cached)
Traceback (most recent call last):
  File "/home/kururu/github/openseg.pytorch/main.py", line 227, in <module>
    model.train()
  File "/home/kururu/github/openseg.pytorch/segmentor/trainer.py", line 365, in train
    self.__train()
  File "/home/kururu/github/openseg.pytorch/segmentor/trainer.py", line 240, in __train
    self.__val()
  File "/home/kururu/github/openseg.pytorch/segmentor/trainer.py", line 308, in __val
    outputs = self.seg_net(*inputs)
  File "/home/kururu/anaconda3/envs/kururudev-torch-1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kururu/anaconda3/envs/kururudev-torch-1-0/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 442, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/kururu/anaconda3/envs/kururudev-torch-1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kururu/github/openseg.pytorch/lib/models/nets/ocnet.py", line 58, in forward
    x = self.oc_module(x)
  File "/home/kururu/anaconda3/envs/kururudev-torch-1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kururu/github/openseg.pytorch/lib/models/modules/base_oc_block.py", line 153, in forward
    priors = [stage(feats) for stage in self.stages]
  File "/home/kururu/github/openseg.pytorch/lib/models/modules/base_oc_block.py", line 153, in <listcomp>
    priors = [stage(feats) for stage in self.stages]
  File "/home/kururu/anaconda3/envs/kururudev-torch-1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kururu/github/openseg.pytorch/lib/models/modules/base_oc_block.py", line 89, in forward
    sim_map = (self.key_channels**-.5) * sim_map
RuntimeError: CUDA out of memory. Tried to allocate 4.10 GiB (GPU 1; 10.92 GiB total capacity; 5.46 GiB already allocated; 523.50 MiB free; 4.38 GiB cached)

**Comment by PkuRainBow** [comment]
Considering the OOM only occurs during the evaluation steps when training, we recommend you set the **test_interval** to be very large number, e.g. 999,999 to avoid it. Then after finished the training, you can evaluate the checkpoints separately.
