### ISSUE TITLE
all pixel values as 0 during hrnet-ocr inference in label folder and 255 in label_w_segfix with segfix

### ISSUE THREAD

**Issue by thegigasurgeon** [openseg-group/openseg.pytorch#72]
I have been trying to reproduce the results with pretrained weights using "bash scripts/cityscapes/hrnet/run_h_48_d_4_ocr.sh val".
Inside the vis folder that is generated, the outputs are fine. But inside the label folder, every pixel value is 0.

After trying segfix, label_w_segfix folder is generated. Every pixel for every image in that folder is 255. Help me out.

**Comment by thegigasurgeon** [comment]
I have found the issue. In openseg.pytorch/segmentor/tester.py , before the line  "# colorize the label-map" we are saving the image. If saving the original label_img_ numpy array with cv2.imwrite(), the issue is resolved and the labels are correctly produced.

**Comment by ZSL98** [comment]
@thegigasurgeon Many thanks!

**Comment by Wang-Shuxuan** [comment]
@ZSL98 @thegigasurgeon Hello, I have met the same problem. I want to know how to change the code block, could you please tell me with more details?

**Comment by thegigasurgeon** [comment]
@Wang in the file openseg.pytorch/segmentor/tester.py, replace "ImageHelper.save(label_img_, label_path)" with "cv2.imwrite(label_path, label_img_) ".

**Comment by Wang-Shuxuan** [comment]
> @Wang in the file openseg.pytorch/segmentor/tester.py, replace "ImageHelper.save(label_img_, label_path)" with "cv2.imwrite(label_path, label_img_) ".
I tried the method, but I met another issue as follows:
" 
Traceback (most recent call last):
  File "main.py", line 228, in <module>
    model.test()
  File "/home/icra/extenddisk/openseg.pytorch-master/segmentor/tester.py", line 194, in test
    cv2.imwrite(label_path, label_img_)
cv2.error: OpenCV(4.5.4-dev) :-1: error: (-5:Bad argument) in function 'imwrite'
> Overload resolution failed:
>  - img is not a numpy array, neither a scalar
>  - Expected Ptr<cv::UMat> for argument 'img'

evaluate the result...
ERROR: Found no prediction for ground truth /home/icra/extenddisk/openseg.pytorch-master/DATA_ROOT/cityscapes/val/label/munster_000049_000019_leftImg8bit.png
"
 In openseg.pytorch/segmentor/tester.py , at L189 “label_img_ = Image.fromarray(label_img_, 'P')”, the format of the label_img_ seems Image.Image, not array.

**Comment by thegigasurgeon** [comment]
@Wang in the file segmentor/tester.py near line no 189 to 193

                   replace 

                   "label_img_ = Image.fromarray(label_img_, 'P')
                    Log.info('{:4d}/{:4d} label map generated'.format(image_id, self.test_size))
                    label_path = os.path.join(self.save_dir, "label/", '{}.png'.format(names[k]))
                    FileHelper.make_dirs(label_path, is_file=True)
                    ImageHelper.save(label_img_, label_path)"

                   with
                    
                  " alt_image = label_img_
                    label_img_ = Image.fromarray(label_img_, 'P')
                    Log.info('{:4d}/{:4d} label map generated'.format(image_id, self.test_size))
                    label_path = os.path.join(self.save_dir, "label/", '{}.png'.format(names[k]))
                    FileHelper.make_dirs(label_path, is_file=True)
                    #ImageHelper.save(label_img_, label_path)
                    cv2.imwrite(label_path, alt_image)"

For me, this fixed the problem. You can also try visualisizing the image array before these lines to see if the values are correct. For me, this had fixed the problem.
